sonar.organization=usdot-fhwa-stol
sonar.projectKey=usdot-fhwa-stol_ns3-federate
sonar.projectName=ns3-federate
sonar.projectVersion=4.13.0
sonar.sources=src
sonar.coverage.exclusions=**/test/**
sonar.scm.provider=git
sonar.sourceEncoding=UTF-8
sonar.cfamily.compile-commands=bw-output/compile_commands.json